version: "3.7"
services:
  node-vue:
    build: 
      context: .
    container_name: shopping_web_frontend
    image: chuchunchia/shopping_web_frontend
    ports:
      - '5173:5173'
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      VITE_APP_API: http://localhost:3000/
    volumes:
      - ./src:/app/src
      - ./helpers:/app/helpers
      - ./vite.config.js:/app/vite.config.js
    networks:
      - shopping_web
    command: >
      sh -c "./wait-for-it.sh shopping_web_backend:3000 -t 60 -- npm run dev"

networks:
  shopping_web:

